-- Insert sample users
INSERT INTO users (id, email, name, avatar) VALUES
('550e8400-e29b-41d4-a716-446655440001', 'moviebuff@example.com', 'MovieBuff2024', '/placeholder-user.jpg'),
('550e8400-e29b-41d4-a716-446655440002', 'cinemalover@example.com', 'CinemaLover', '/placeholder-user.jpg'),
('550e8400-e29b-41d4-a716-446655440003', 'filmcritic@example.com', 'FilmCritic99', '/placeholder-user.jpg')
ON CONFLICT (id) DO NOTHING;

-- Insert sample movies
INSERT INTO movies (id, title, year, rating, duration, genre, director, cast, poster, backdrop, description, plot) VALUES
(1, 'The Dark Knight', 2008, 9.0, '152 min', 
 ARRAY['Action', 'Crime', 'Drama'], 
 'Christopher Nolan', 
 ARRAY['Christian Bale', 'Heath Ledger', 'Aaron Eckhart', 'Michael Caine'],
 '/dark-knight-poster.png',
 '/dark-knight-inspired-scene.png',
 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
 'Batman raises the stakes in his war on crime with the help of Lt. Jim Gordon and District Attorney Harvey Dent. Together, they work to dismantle the remaining criminal organizations that plague the streets. However, their partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.'),

(2, 'Inception', 2010, 8.8, '148 min',
 ARRAY['Action', 'Sci-Fi', 'Thriller'],
 'Christopher Nolan',
 ARRAY['Leonardo DiCaprio', 'Marion Cotillard', 'Tom Hardy', 'Ellen Page'],
 '/inception-movie-poster.png',
 '/inception-movie-scene.png',
 'A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
 'Dom Cobb is a skilled thief, the absolute best in the dangerous art of extraction, stealing valuable secrets from deep within the subconscious during the dream state, when the mind is at its most vulnerable.'),

(3, 'Pulp Fiction', 1994, 8.9, '154 min',
 ARRAY['Crime', 'Drama'],
 'Quentin Tarantino',
 ARRAY['John Travolta', 'Uma Thurman', 'Samuel L. Jackson', 'Bruce Willis'],
 '/pulp-fiction-poster.png',
 '/pulp-fiction-backdrop.png',
 'The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.',
 'A burger-loving hit man, his philosophical partner, a drug-addled gangster''s moll and a washed-up boxer converge in this sprawling, comedic crime caper.'),

(4, 'The Shawshank Redemption', 1994, 9.3, '142 min',
 ARRAY['Drama'],
 'Frank Darabont',
 ARRAY['Tim Robbins', 'Morgan Freeman', 'Bob Gunton', 'William Sadler'],
 '/shawshank-redemption-poster.png',
 '/shawshank-backdrop.png',
 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
 'Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden.'),

(5, 'Dune: Part Two', 2024, 8.5, '166 min',
 ARRAY['Action', 'Adventure', 'Drama'],
 'Denis Villeneuve',
 ARRAY['Timothée Chalamet', 'Zendaya', 'Rebecca Ferguson', 'Josh Brolin'],
 '/dune-part-two-poster.png',
 '/dune-backdrop.png',
 'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.',
 'Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a warpath of revenge against the conspirators who destroyed his family.'),

-- Insert additional movies (21-50)
INSERT INTO movies (id, title, year, rating, duration, genre, director, cast, poster, backdrop, description, plot) VALUES
(21, 'The Godfather', 1972, 9.2, '175 min', 
 ARRAY['Crime', 'Drama'], 
 'Francis Ford Coppola', 
 ARRAY['Marlon Brando', 'Al Pacino', 'James Caan', 'Diane Keaton'],
 '/godfather-poster.png',
 '/godfather-backdrop.png',
 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
 'Don Vito Corleone, head of a mafia family, decides to hand over his empire to his youngest son Michael. However, his decision unintentionally puts the lives of his loved ones in grave danger.'),

(22, 'Schindler''s List', 1993, 9.0, '195 min',
 ARRAY['Biography', 'Drama', 'History'],
 'Steven Spielberg',
 ARRAY['Liam Neeson', 'Ralph Fiennes', 'Ben Kingsley', 'Caroline Goodall'],
 '/schindlers-list-poster.png',
 '/schindlers-list-backdrop.png',
 'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.',
 'Oskar Schindler, a German industrialist and member of the Nazi party, tries to save his Jewish employees after witnessing the persecution of Jews in Poland.'),

(23, 'The Lord of the Rings: The Return of the King', 2003, 9.0, '201 min',
 ARRAY['Action', 'Adventure', 'Drama'],
 'Peter Jackson',
 ARRAY['Elijah Wood', 'Viggo Mortensen', 'Ian McKellen', 'Orlando Bloom'],
 '/lotr-return-king-poster.png',
 '/lotr-return-king-backdrop.png',
 'Gandalf and Aragorn lead the World of Men against Sauron''s army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.',
 'The final confrontation between the forces of good and evil fighting for control of the future of Middle-earth. Frodo and Sam reach Mordor in their quest to destroy the One Ring.'),

(24, 'Forrest Gump', 1994, 8.8, '142 min',
 ARRAY['Drama', 'Romance'],
 'Robert Zemeckis',
 ARRAY['Tom Hanks', 'Robin Wright', 'Gary Sinise', 'Sally Field'],
 '/forrest-gump-poster.png',
 '/forrest-gump-backdrop.png',
 'The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75.',
 'Forrest Gump, while not intelligent, has accidentally been present at many historic moments, but his true love, Jenny Curran, eludes him.'),

(25, 'Fight Club', 1999, 8.8, '139 min',
 ARRAY['Drama'],
 'David Fincher',
 ARRAY['Brad Pitt', 'Edward Norton', 'Helena Bonham Carter', 'Meat Loaf'],
 '/fight-club-poster.png',
 '/fight-club-backdrop.png',
 'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into an anarchist organization.',
 'A depressed man suffering from insomnia meets a strange soap salesman named Tyler Durden and soon finds himself living in his squalid house after his perfect apartment is destroyed.'),

(26, 'The Matrix', 1999, 8.7, '136 min',
 ARRAY['Action', 'Sci-Fi'],
 'Lana Wachowski',
 ARRAY['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss', 'Hugo Weaving'],
 '/matrix-poster.png',
 '/matrix-backdrop.png',
 'When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.',
 'A computer programmer is led to fight an underground war against powerful computers who have constructed his entire reality with a system called the Matrix.'),

(27, 'Goodfellas', 1990, 8.7, '146 min',
 ARRAY['Biography', 'Crime', 'Drama'],
 'Martin Scorsese',
 ARRAY['Robert De Niro', 'Ray Liotta', 'Joe Pesci', 'Lorraine Bracco'],
 '/goodfellas-poster.png',
 '/goodfellas-backdrop.png',
 'The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito.',
 'A young man grows up in the mob and works very hard to advance himself through the ranks. He enjoys his life of money and luxury, but is oblivious to the horror that he causes.'),

(28, 'The Lord of the Rings: The Fellowship of the Ring', 2001, 8.8, '178 min',
 ARRAY['Action', 'Adventure', 'Drama'],
 'Peter Jackson',
 ARRAY['Elijah Wood', 'Ian McKellen', 'Orlando Bloom', 'Sean Bean'],
 '/lotr-fellowship-poster.png',
 '/lotr-fellowship-backdrop.png',
 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.',
 'A young hobbit, Frodo, who has inherited a mysterious ring from his uncle Bilbo, must leave his home in order to keep it from falling into the hands of its evil creator.'),

(29, 'Star Wars: Episode V - The Empire Strikes Back', 1980, 8.7, '124 min',
 ARRAY['Action', 'Adventure', 'Fantasy'],
 'Irvin Kershner',
 ARRAY['Mark Hamill', 'Harrison Ford', 'Carrie Fisher', 'Billy Dee Williams'],
 '/empire-strikes-back-poster.png',
 '/empire-strikes-back-backdrop.png',
 'After the Rebels are brutally overpowered by the Empire on the ice planet Hoth, Luke Skywalker begins Jedi training with Yoda, while his friends are pursued across the galaxy.',
 'Luke Skywalker, Han Solo, Princess Leia and Chewbacca face attack by the Imperial forces and its AT-AT walkers on the ice planet Hoth.'),

(30, 'One Flew Over the Cuckoo''s Nest', 1975, 8.7, '133 min',
 ARRAY['Drama'],
 'Milos Forman',
 ARRAY['Jack Nicholson', 'Louise Fletcher', 'Danny DeVito', 'Christopher Lloyd'],
 '/cuckoos-nest-poster.png',
 '/cuckoos-nest-backdrop.png',
 'In the Fall of 1963, a Korean War veteran and criminal pleads insanity and is admitted to a mental institution, where he rallies up the scared patients against the tyrannical nurse.',
 'A criminal pleads insanity and is admitted to a mental institution, where he rebels against the oppressive nurse and rallies up the scared patients.'),

(31, 'Interstellar', 2014, 8.6, '169 min',
 ARRAY['Adventure', 'Drama', 'Sci-Fi'],
 'Christopher Nolan',
 ARRAY['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain', 'Michael Caine'],
 '/interstellar-poster.png',
 '/interstellar-backdrop.png',
 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity''s survival.',
 'Earth''s future has been riddled by disasters, famines, and droughts. There is only one way to ensure mankind''s survival: Interstellar travel.'),

(32, 'The Departed', 2006, 8.5, '151 min',
 ARRAY['Crime', 'Drama', 'Thriller'],
 'Martin Scorsese',
 ARRAY['Leonardo DiCaprio', 'Matt Damon', 'Jack Nicholson', 'Mark Wahlberg'],
 '/departed-poster.png',
 '/departed-backdrop.png',
 'An undercover cop and a police informant play a cat and mouse game with each other as they attempt to find out each other''s identity while being undercover in the Irish mob in Boston.',
 'Two men from opposite sides of the law are undercover within the Massachusetts State Police and the Irish mafia, but violence and bloodshed boil when discoveries are made.'),

(33, 'The Silence of the Lambs', 1991, 8.6, '118 min',
 ARRAY['Crime', 'Drama', 'Thriller'],
 'Jonathan Demme',
 ARRAY['Jodie Foster', 'Anthony Hopkins', 'Scott Glenn', 'Ted Levine'],
 '/silence-lambs-poster.png',
 '/silence-lambs-backdrop.png',
 'A young FBI cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.',
 'Clarice Starling, a young FBI trainee, is asked to carry out an errand by Jack Crawford, the head of the FBI division that draws up psychological profiles of serial killers.'),

(34, 'Saving Private Ryan', 1998, 8.6, '169 min',
 ARRAY['Drama', 'War'],
 'Steven Spielberg',
 ARRAY['Tom Hanks', 'Matt Damon', 'Tom Sizemore', 'Edward Burns'],
 '/saving-private-ryan-poster.png',
 '/saving-private-ryan-backdrop.png',
 'Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.',
 'Captain John Miller takes his men behind enemy lines to find Private James Ryan, whose three brothers have been killed in combat.'),

(35, 'The Green Mile', 1999, 8.6, '189 min',
 ARRAY['Crime', 'Drama', 'Fantasy'],
 'Frank Darabont',
 ARRAY['Tom Hanks', 'Michael Clarke Duncan', 'David Morse', 'Bonnie Hunt'],
 '/green-mile-poster.png',
 '/green-mile-backdrop.png',
 'The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.',
 'Paul Edgecomb, the head guard of a prison, meets an inmate, John Coffey, a black man who is accused of murdering two girls. His life changes drastically when he discovers that John has a special gift.'),

(36, 'Se7en', 1995, 8.6, '127 min',
 ARRAY['Crime', 'Drama', 'Mystery'],
 'David Fincher',
 ARRAY['Morgan Freeman', 'Brad Pitt', 'Kevin Spacey', 'Gwyneth Paltrow'],
 '/seven-poster.png',
 '/seven-backdrop.png',
 'Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.',
 'A serial killer begins murdering people according to the seven deadly sins. Two detectives, one new to the city and the other about to retire, are tasked with apprehending the criminal.'),

(37, 'The Prestige', 2006, 8.5, '130 min',
 ARRAY['Drama', 'Mystery', 'Sci-Fi'],
 'Christopher Nolan',
 ARRAY['Christian Bale', 'Hugh Jackman', 'Scarlett Johansson', 'Michael Caine'],
 '/prestige-poster.png',
 '/prestige-backdrop.png',
 'After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.',
 'Two friends and fellow magicians become bitter enemies after a sudden tragedy. As they devote themselves to this rivalry, they make sacrifices that bring them fame but with terrible consequences.'),

(38, 'Terminator 2: Judgment Day', 1991, 8.6, '137 min',
 ARRAY['Action', 'Sci-Fi'],
 'James Cameron',
 ARRAY['Arnold Schwarzenegger', 'Linda Hamilton', 'Edward Furlong', 'Robert Patrick'],
 '/terminator-2-poster.png',
 '/terminator-2-backdrop.png',
 'A cyborg, identical to the one who failed to kill Sarah Connor, must now protect her ten-year-old son John from a more advanced and powerful cyborg.',
 'A shape-shifting cyborg is sent back from the future to kill John Connor before he can grow up to lead the resistance.'),

(39, 'The Lion King', 1994, 8.5, '88 min',
 ARRAY['Animation', 'Adventure', 'Drama'],
 'Roger Allers',
 ARRAY['Matthew Broderick', 'Jeremy Irons', 'James Earl Jones', 'Whoopi Goldberg'],
 '/lion-king-poster.png',
 '/lion-king-backdrop.png',
 'Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.',
 'A young lion prince is cast out of his pride by his cruel uncle, who claims he killed his father. While the uncle rules with an iron paw, the prince grows up beyond the Savannah.'),

(40, 'Back to the Future', 1985, 8.5, '116 min',
 ARRAY['Adventure', 'Comedy', 'Sci-Fi'],
 'Robert Zemeckis',
 ARRAY['Michael J. Fox', 'Christopher Lloyd', 'Lea Thompson', 'Crispin Glover'],
 '/back-to-future-poster.png',
 '/back-to-future-backdrop.png',
 'Marty McFly, a 17-year-old high school student, is accidentally sent 30 years into the past in a time-traveling DeLorean invented by his close friend, the maverick scientist Doc Brown.',
 'A teenager is accidentally sent 30 years into the past in a time-traveling DeLorean invented by his friend, Dr. Emmett Brown.'),

(41, 'Gladiator', 2000, 8.5, '155 min',
 ARRAY['Action', 'Adventure', 'Drama'],
 'Ridley Scott',
 ARRAY['Russell Crowe', 'Joaquin Phoenix', 'Connie Nielsen', 'Oliver Reed'],
 '/gladiator-poster.png',
 '/gladiator-backdrop.png',
 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.',
 'Maximus is a powerful Roman general, loved by the people and the aging Emperor, Marcus Aurelius. Before his death, the Emperor chooses Maximus to be his heir over his own son, Commodus.'),

(42, 'Apocalypse Now', 1979, 8.4, '147 min',
 ARRAY['Drama', 'Mystery', 'War'],
 'Francis Ford Coppola',
 ARRAY['Martin Sheen', 'Marlon Brando', 'Robert Duvall', 'Dennis Hopper'],
 '/apocalypse-now-poster.png',
 '/apocalypse-now-backdrop.png',
 'A U.S. Army officer serving in Vietnam is tasked with assassinating a renegade Special Forces Colonel who sees himself as a god.',
 'During the Vietnam War, Captain Willard is sent on a dangerous mission into Cambodia to assassinate a renegade colonel who has set himself up as a god among a local tribe.'),

(43, 'The Usual Suspects', 1995, 8.5, '106 min',
 ARRAY['Crime', 'Mystery', 'Thriller'],
 'Bryan Singer',
 ARRAY['Kevin Spacey', 'Gabriel Byrne', 'Chazz Palminteri', 'Stephen Baldwin'],
 '/usual-suspects-poster.png',
 '/usual-suspects-backdrop.png',
 'A sole survivor tells of the twisty events leading up to a horrific gun battle on a boat, which began when five criminals met at a seemingly random police lineup.',
 'The only survivor of a pier shoot-out tells the story of how a notorious criminal influenced the events that began with five criminals meeting in a seemingly random police lineup.'),

(44, 'Léon: The Professional', 1994, 8.5, '110 min',
 ARRAY['Action', 'Crime', 'Drama'],
 'Luc Besson',
 ARRAY['Jean Reno', 'Gary Oldman', 'Natalie Portman', 'Danny Aiello'],
 '/leon-poster.png',
 '/leon-backdrop.png',
 '12-year-old Mathilda is reluctantly taken in by Léon, a professional assassin, after her family is murdered. An unusual relationship forms as she becomes his protégée and learns the assassin''s trade.',
 'Mathilda, a 12-year-old girl, is reluctantly taken in by Léon, a professional assassin, after her family is murdered by corrupt DEA agents.'),

(45, 'Casablanca', 1942, 8.5, '102 min',
 ARRAY['Drama', 'Romance', 'War'],
 'Michael Curtiz',
 ARRAY['Humphrey Bogart', 'Ingrid Bergman', 'Paul Henreid', 'Claude Rains'],
 '/casablanca-poster.png',
 '/casablanca-backdrop.png',
 'A cynical expatriate American cafe owner struggles to decide whether or not to help his former lover and her fugitive husband escape the Nazis in French Morocco.',
 'In Casablanca in December 1941, a cynical American expatriate encounters a former lover, with unforeseen complications.'),

(46, 'Psycho', 1960, 8.5, '109 min',
 ARRAY['Horror', 'Mystery', 'Thriller'],
 'Alfred Hitchcock',
 ARRAY['Anthony Perkins', 'Janet Leigh', 'Vera Miles', 'John Gavin'],
 '/psycho-poster.png',
 '/psycho-backdrop.png',
 'A Phoenix secretary embezzles $40,000 from her employer''s client, goes on the run and checks into a remote motel run by a young man under the domination of his mother.',
 'A secretary on the run for embezzlement takes refuge at a secluded California motel owned by a repressed man and his overbearing mother.'),

(47, 'Rear Window', 1954, 8.5, '112 min',
 ARRAY['Mystery', 'Thriller'],
 'Alfred Hitchcock',
 ARRAY['James Stewart', 'Grace Kelly', 'Wendell Corey', 'Thelma Ritter'],
 '/rear-window-poster.png',
 '/rear-window-backdrop.png',
 'A photographer in a wheelchair spies on his neighbors from his apartment window and becomes convinced one of them has committed murder.',
 'A photographer with a broken leg is confined to a wheelchair in his apartment. He becomes obsessed with watching his neighbors through his rear window.'),

(48, 'City Lights', 1931, 8.5, '87 min',
 ARRAY['Comedy', 'Drama', 'Romance'],
 'Charles Chaplin',
 ARRAY['Charles Chaplin', 'Virginia Cherrill', 'Florence Lee', 'Harry Myers'],
 '/city-lights-poster.png',
 '/city-lights-backdrop.png',
 'With the aid of a wealthy erratic tippler, a dewy-eyed tramp who has fallen in love with a sightless flower girl pursues a unique opportunity to help her medically.',
 'The Tramp struggles to help a blind flower girl he has fallen in love with and a millionaire who only recognizes him when drunk.'),

(49, 'Memento', 2000, 8.4, '113 min',
 ARRAY['Mystery', 'Thriller'],
 'Christopher Nolan',
 ARRAY['Guy Pearce', 'Carrie-Anne Moss', 'Joe Pantoliano', 'Mark Boone Junior'],
 '/memento-poster.png',
 '/memento-backdrop.png',
 'A man with short-term memory loss attempts to track down his wife''s murderer.',
 'Leonard Shelby, an insurance investigator, suffers from anterograde amnesia and uses notes and tattoos to hunt for the man he thinks killed his wife.'),

(50, 'Raiders of the Lost Ark', 1981, 8.4, '115 min',
 ARRAY['Action', 'Adventure'],
 'Steven Spielberg',
 ARRAY['Harrison Ford', 'Karen Allen', 'Paul Freeman', 'Ronald Lacey'],
 '/raiders-lost-ark-poster.png',
 '/raiders-lost-ark-backdrop.png',
 'In 1936, archaeologist and adventurer Indiana Jones is hired by the U.S. government to find the Ark of the Covenant before Adolf Hitler''s Nazis can obtain its awesome powers.',
 'Archaeologist Indiana Jones races against time to retrieve a legendary artifact that can change the course of history.')

-- Insert Lifetime Movies (51-100)
INSERT INTO movies (id, title, year, rating, duration, genre, director, cast, poster, backdrop, description, plot) VALUES
(51, 'The Perfect Mother', 2023, 6.8, '87 min',
 ARRAY['Drama', 'Thriller'],
 'Curtis Crawford',
 ARRAY['Annie Wersching', 'Bree Williamson', 'Jason Cermak', 'Zibby Allen'],
 '/lifetime-perfect-mother-poster.png',
 '/lifetime-perfect-mother-backdrop.png',
 'A mother''s world is turned upside down when her teenage daughter goes missing, and she discovers dark secrets about her family.',
 'When her teenage daughter disappears, a desperate mother uncovers a web of lies and deception that threatens to destroy everything she thought she knew about her family.'),

(52, 'Stolen by My Mother: The Kamiyah Mobley Story', 2020, 7.2, '87 min',
 ARRAY['Biography', 'Drama'],
 'Robin Hays',
 ARRAY['Rayven Ferrell', 'Niecy Nash', 'Ta''Rhonda Jones', 'Roger Cross'],
 '/lifetime-stolen-mother-poster.png',
 '/lifetime-stolen-mother-backdrop.png',
 'The true story of Kamiyah Mobley, who was kidnapped as a newborn and raised by her abductor for 18 years.',
 'Based on a true story, this film follows the incredible journey of a young woman who discovers that the woman who raised her actually kidnapped her as a baby.'),

(53, 'The College Admissions Scandal', 2019, 6.9, '87 min',
 ARRAY['Drama', 'Crime'],
 'Adam Salky',
 ARRAY['Penelope Ann Miller', 'Mia Kirshner', 'Michael Shanks', 'Sarah Dugdale'],
 '/lifetime-college-scandal-poster.png',
 '/lifetime-college-scandal-backdrop.png',
 'A dramatization of the 2019 college admissions bribery scandal that rocked the nation.',
 'Two wealthy mothers navigate the competitive world of college admissions, resorting to bribery and fraud to secure their children''s futures at prestigious universities.'),

(54, 'The Wrong Cheerleader', 2019, 6.5, '87 min',
 ARRAY['Thriller', 'Drama'],
 'David DeCoteau',
 ARRAY['Vivica A. Fox', 'Jackée Harry', 'Corin Nemec', 'Cristine Prosperi'],
 '/lifetime-wrong-cheerleader-poster.png',
 '/lifetime-wrong-cheerleader-backdrop.png',
 'A mother becomes suspicious when her daughter joins the cheerleading squad and strange accidents start happening.',
 'When Becky joins the cheerleading squad, her mother notices that accidents keep happening to the other girls. She begins to suspect that someone is targeting the team.'),

(55, 'Escaping the NXIVM Cult: A Mother''s Fight to Save Her Daughter', 2019, 7.1, '87 min',
 ARRAY['Biography', 'Drama'],
 'Lisa Robinson',
 ARRAY['Andrea Roth', 'Jasper Polish', 'Peter Facinelli', 'Sara Fletcher'],
 '/lifetime-nxivm-poster.png',
 '/lifetime-nxivm-backdrop.png',
 'Based on the true story of a mother''s desperate fight to save her daughter from the NXIVM cult.',
 'A mother races against time to rescue her daughter from a dangerous cult that has brainwashed her into believing their twisted ideology.'),

-- Continue with remaining Lifetime movies (56-100)
(56, 'The Cheerleader Murders', 2016, 6.3, '87 min',
 ARRAY['Thriller', 'Mystery'],
 'David Jackson',
 ARRAY['Samantha Boscarino', 'Irene Chiang', 'Blaine Kern III', 'Devin Crittenden'],
 '/lifetime-cheerleader-murders-poster.png',
 '/lifetime-cheerleader-murders-backdrop.png',
 'A high school cheerleader becomes the target of a killer who is systematically murdering members of the squad.',
 'When cheerleaders start turning up dead, the remaining squad members must figure out who the killer is before they become the next victims.'),

(57, 'The Bad Seed', 2018, 7.0, '87 min',
 ARRAY['Thriller', 'Drama'],
 'Rob Lowe',
 ARRAY['Rob Lowe', 'Mckenna Grace', 'Sarah Dugdale', 'Marci T. House'],
 '/lifetime-bad-seed-poster.png',
 '/lifetime-bad-seed-backdrop.png',
 'A father begins to suspect that his seemingly perfect young daughter may be a sociopath.',
 'David Grossman''s life changes forever when he begins to suspect that his 9-year-old daughter Emma may be responsible for a series of deadly accidents.'),

(58, 'The Wrong Student', 2017, 6.4, '87 min',
 ARRAY['Thriller', 'Drama'],
 'David DeCoteau',
 ARRAY['Jessica Morris', 'Vivica A. Fox', 'Jason-Shane Scott', 'Victoria Konefal'],
 '/lifetime-wrong-student-poster.png',
 '/lifetime-wrong-student-backdrop.png',
 'A college professor''s life spirals out of control when she becomes involved with a dangerous student.',
 'Professor Kelly Winters thinks she''s helping a struggling student, but soon discovers that he has a dark obsession with her that threatens her career and her life.'),

(59, 'Mommy''s Little Girl', 2016, 6.6, '87 min',
 ARRAY['Thriller', 'Drama'],
 'Curtis Crawford',
 ARRAY['Fiona Gubelmann', 'Kendra Spade', 'Morgan Taylor Campbell', 'Brent Stait'],
 '/lifetime-mommys-little-girl-poster.png',
 '/lifetime-mommys-little-girl-backdrop.png',
 'A mother''s relationship with her teenage daughter becomes dangerously obsessive.',
 'Claudia''s overprotective nature toward her daughter Rachel escalates to dangerous levels when she discovers Rachel is growing up and pulling away from her.'),

(60, 'The Wrong Nanny', 2017, 6.7, '87 min',
 ARRAY['Thriller', 'Drama'],
 'David DeCoteau',
 ARRAY['Lindsay Hartley', 'Freya Tingley', 'Brody Hutzler', 'Cynthia Watros'],
 '/lifetime-wrong-nanny-poster.png',
 '/lifetime-wrong-nanny-backdrop.png',
 'A family hires what seems like the perfect nanny, but she has a dangerous hidden agenda.',
 'Stella Armstrong hires a live-in nanny to help with her twin boys, but the seemingly perfect caregiver harbors dark secrets that threaten the entire family.'),

-- Add remaining movies 61-100 with similar structure...
(61, 'A Mother''s Nightmare', 2012, 6.2, '87 min',
 ARRAY['Drama', 'Thriller'],
 'Vic Sarin',
 ARRAY['Annabeth Gish', 'Jessica Lowndes', 'Grant Bowler', 'Jay Brazeau'],
 '/lifetime-mothers-nightmare-poster.png',
 '/lifetime-mothers-nightmare-backdrop.png',
 'A mother becomes concerned when her teenage son starts dating a manipulative and dangerous older woman.',
 'Vanessa starts to worry when her son Chris begins dating Carol, a beautiful but troubled woman with a dark past.'),

(62, 'The Pregnancy Project', 2012, 7.3, '87 min',
 ARRAY['Drama'],
 'Norman Buckley',
 ARRAY['Alexa PenaVega', 'Matt Ward', 'Sarah Dugdale', 'Josie Loren'],
 '/lifetime-pregnancy-project-poster.png',
 '/lifetime-pregnancy-project-backdrop.png',
 'A high school student pretends to be pregnant for a class project, but her lie spirals out of control.',
 'Gaby Rodriguez fakes a pregnancy for a school project to see how her friends and family will react.'),

(63, 'Liz & Dick', 2012, 4.1, '87 min',
 ARRAY['Biography', 'Drama', 'Romance'],
 'Lloyd Kramer',
 ARRAY['Lindsay Lohan', 'Grant Bowler', 'Tanya Fischer', 'David Hunt'],
 '/lifetime-liz-dick-poster.png',
 '/lifetime-liz-dick-backdrop.png',
 'A dramatization of the tumultuous relationship between Elizabeth Taylor and Richard Burton.',
 'The story of Elizabeth Taylor and Richard Burton''s passionate and often volatile romance.'),

(64, 'Drew Peterson: Untouchable', 2012, 5.5, '87 min',
 ARRAY['Biography', 'Crime', 'Drama'],
 'Robert Iscove',
 ARRAY['Rob Lowe', 'Kaley Cuoco', 'Catherine O''Hara', 'Cara Buono'],
 '/lifetime-drew-peterson-poster.png',
 '/lifetime-drew-peterson-backdrop.png',
 'The story of Drew Peterson, a former police officer suspected of murdering his wife.',
 'The life and crimes of Drew Peterson, a police officer who was suspected of killing his third wife and whose fourth wife disappeared.'),

(65, 'Steel Magnolias', 2012, 6.6, '87 min',
 ARRAY['Comedy', 'Drama'],
 'Kenny Leon',
 ARRAY['Queen Latifah', 'Phylicia Rashad', 'Jill Scott', 'Adepero Oduye'],
 '/lifetime-steel-magnolias-poster.png',
 '/lifetime-steel-magnolias-backdrop.png',
 'A remake of the classic film about a group of women in a small Louisiana town who support each other through life''s challenges.',
 'A group of strong women in a small Southern town bond and support each other through life''s joys and sorrows.'),

(66, 'Anna Nicole', 2013, 4.5, '87 min',
 ARRAY['Biography', 'Drama'],
 'Mary Harron',
 ARRAY['Agnes Bruckner', 'Martin Landau', 'Virginia Madsen', 'Adam Goldberg'],
 '/lifetime-anna-nicole-poster.png',
 '/lifetime-anna-nicole-backdrop.png',
 'The story of Anna Nicole Smith, from her early life to her tragic death.',
 'The rise and fall of Anna Nicole Smith, from her humble beginnings to her fame and untimely death.'),

(67, 'Flowers in the Attic', 2014, 6.3, '87 min',
 ARRAY['Drama', 'Horror', 'Mystery'],
 'Deborah Chow',
 ARRAY['Kiernan Shipka', 'Ellen Burstyn', 'Mason Dye', 'Heather Graham'],
 '/lifetime-flowers-attic-poster.png',
 '/lifetime-flowers-attic-backdrop.png',
 'Four children are locked away in an attic by their cruel grandmother after their father dies.',
 'After their father dies, four children are confined to an attic by their grandmother, who is determined to keep them hidden from the world.'),

(68, 'Petals on the Wind', 2014, 6.1, '87 min',
 ARRAY['Drama', 'Thriller'],
 'Karen Moncrieff',
 ARRAY['Rose McIver', 'Wyatt Nash', 'Bailey Buntain', 'Ellen Burstyn'],
 '/lifetime-petals-wind-poster.png',
 '/lifetime-petals-wind-backdrop.png',
 'Years after escaping from their grandmother''s attic, the Dollanganger children struggle to overcome their past.',
 'Ten years after escaping from their grandmother''s attic, Cathy, Chris, and Carrie struggle to lead normal lives, but their past continues to haunt them.'),

(69, 'If There Be Thorns', 2015, 5.8, '87 min',
 ARRAY['Drama', 'Thriller'],
 'Nancy Savoca',
 ARRAY['Heather Graham', 'Jason Lewis', 'Rachael Carpani', 'James Maslow'],
 '/lifetime-if-there-be-thorns-poster.png',
 '/lifetime-if-there-be-thorns-backdrop.png',
 'Cathy and Chris face a shocking revelation when their son Jory becomes obsessed with his mysterious neighbor.',
 'Years after escaping the attic, Cathy and Chris live as husband and wife and try to keep their past a secret from their children. However, their son Jory becomes fascinated with their mysterious neighbor, Corinne.'),

(70, 'Seeds of Yesterday', 2015, 5.6, '87 min',
 ARRAY['Drama', 'Thriller'],
 'Shawn Ku',
 ARRAY['Rachael Carpani', 'Jason Lewis', 'James Maslow', 'Sammi Hanratty'],
 '/lifetime-seeds-yesterday-poster.png',
 '/lifetime-seeds-yesterday-backdrop.png',
 'The Dollanganger children struggle to cope with the dark secrets of their past as they face new challenges.',
 'Years after the events of "If There Be Thorns," the Dollanganger family continues to be haunted by their past, and new secrets threaten to destroy them.'),

(71, 'Aaliyah: The Princess of R&B', 2014, 4.0, '87 min',
 ARRAY['Biography', 'Drama', 'Music'],
 'Bradley Walsh',
 ARRAY['Alexandra Shipp', 'Rachael Crawford', 'Sterling Jarvis', 'A.J. Saudin'],
 '/lifetime-aaliyah-poster.png',
 '/lifetime-aaliyah-backdrop.png',
 'The life story of R&B singer Aaliyah, from her early career to her tragic death.',
 'The story of Aaliyah''s rise to fame and her untimely death in a plane crash.'),

(72, 'Whitney', 2015, 5.2, '87 min',
 ARRAY['Biography', 'Drama', 'Music'],
 'Angela Bassett',
 ARRAY['Yaya DaCosta', 'Arlen Escarpeta', 'Yolonda Ross', 'Suzzanne Douglas'],
 '/lifetime-whitney-poster.png',
 '/lifetime-whitney-backdrop.png',
 'The tumultuous relationship between Whitney Houston and Bobby Brown.',
 'The story of Whitney Houston''s life and her troubled marriage to Bobby Brown.'),

(73, 'Toni Braxton: Unbreak My Heart', 2016, 6.8, '87 min',
 ARRAY['Biography', 'Drama', 'Music'],
 'Vondie Curtis-Hall',
 ARRAY['Lex Scott Davis', 'Tiffany Hines', 'Gavin Houston', 'Debbi Morgan'],
 '/lifetime-toni-braxton-poster.png',
 '/lifetime-toni-braxton-backdrop.png',
 'The life story of R&B singer Toni Braxton, from her early career to her struggles with lupus.',
 'The story of Toni Braxton''s rise to fame, her struggles with lupus, and her personal life.'),

(74, 'Surviving Compton: Dre, Suge & Michel''le', 2016, 6.5, '87 min',
 ARRAY['Biography', 'Drama', 'Music'],
 'Janice Cooke',
 ARRAY['Rhyon Nicole Brown', 'Curtis Hamilton', 'Jamie Kennedy', 'Michel''le'],
 '/lifetime-surviving-compton-poster.png',
 '/lifetime-surviving-compton-backdrop.png',
 'The story of Michel''le, a singer who was in abusive relationships with Dr. Dre and Suge Knight.',
 'The story of Michel''le, her career, and her abusive relationships with Dr. Dre and Suge Knight.'),

(75, 'Britney Ever After', 2017, 3.5, '87 min',
 ARRAY['Biography', 'Drama', 'Music'],
 'Leslie Libman',
 ARRAY['Natasha Bassett', 'Clayton Chitty', 'Nathan Keyes', 'Peter Benson'],
 '/lifetime-britney-ever-after-poster.png',
 '/lifetime-britney-ever-after-backdrop.png',
 'A dramatization of Britney Spears'' life, from her early career to her struggles with fame.',
 'The story of Britney Spears'' rise to fame, her relationship with Justin Timberlake, and her struggles with the pressures of fame.'),

(76, 'Menendez: Blood Brothers', 2017, 5.8, '87 min',
 ARRAY['Biography', 'Crime', 'Drama'],
 'Fenton Bailey',
 ARRAY['Courtney Love', 'Nico Tortorella', 'Benito Martinez', 'Myko Olivier'],
 '/lifetime-menendez-blood-brothers-poster.png',
 '/lifetime-menendez-blood-brothers-backdrop.png',
 'The story of the Menendez brothers, who were convicted of murdering their parents.',
 'The story of Lyle and Erik Menendez, who were convicted of murdering their wealthy parents.'),

(77, 'Flint', 2017, 7.0, '87 min',
 ARRAY['Drama'],
 'Bruce Beresford',
 ARRAY['Queen Latifah', 'Betsy Brandt', 'Jill Scott', 'Marin Ireland'],
 '/lifetime-flint-poster.png',
 '/lifetime-flint-backdrop.png',
 'The story of the Flint water crisis, told from the perspective of the residents who were affected.',
 'The story of the Flint water crisis and the impact it had on the residents of Flint, Michigan.'),

(78, 'Cocaine Godmother', 2018, 6.2, '87 min',
 ARRAY['Biography', 'Crime', 'Drama'],
 'Guillermo Navarro',
 ARRAY['Catherine Zeta-Jones', 'Jenny Pellicer', 'Alejandro Edda', 'José María Yazpik'],
 '/lifetime-cocaine-godmother-poster.png',
 '/lifetime-cocaine-godmother-backdrop.png',
 'The story of Griselda Blanco, a drug lord who became known as the "Cocaine Godmother."',
 'The story of Griselda Blanco, a ruthless drug lord who built a vast cocaine empire.'),

(79, 'Harry & Meghan: A Royal Romance', 2018, 5.4, '87 min',
 ARRAY['Biography', 'Drama', 'Romance'],
 'Menhaj Huda',
 ARRAY['Parisa Fitz-Henley', 'Murray Fraser', 'Bonnie Soper', 'Burgess Abernethy'],
 '/lifetime-harry-meghan-poster.png',
 '/lifetime-harry-meghan-backdrop.png',
 'The story of Prince Harry and Meghan Markle''s romance.',
 'The story of Prince Harry and Meghan Markle''s relationship, from their first date to their engagement.'),

(80, 'Harry & Meghan: Becoming Royal', 2019, 5.3, '87 min',
 ARRAY['Biography', 'Drama', 'Romance'],
 'Menhaj Huda',
 ARRAY['Tiffany Marie Smith', 'Charlie Field', 'Jordan Whalen', 'Maggie Sullivun'],
 '/lifetime-harry-meghan-becoming-royal-poster.png',
 '/lifetime-harry-meghan-becoming-royal-backdrop.png',
 'The story of Prince Harry and Meghan Markle''s first year of marriage.',
 'The story of Prince Harry and Meghan Markle''s first year as a married couple and their challenges as members of the royal family.'),

(81, 'Patsy & Loretta', 2019, 6.9, '87 min',
 ARRAY['Biography', 'Drama', 'Music'],
 'Callie Khouri',
 ARRAY['Megan Hilty', 'Jessie Mueller', 'Joe Tippett', 'Kyle Schmid'],
 '/lifetime-patsy-loretta-poster.png',
 '/lifetime-patsy-loretta-backdrop.png',
 'The story of the friendship between country music singers Patsy Cline and Loretta Lynn.',
 'The story of the friendship between country music legends Patsy Cline and Loretta Lynn.'),

(82, 'Chris Watts: Confessions of a Killer', 2020, 5.7, '87 min',
 ARRAY['Biography', 'Crime', 'Drama'],
 'Michael Nankin',
 ARRAY['Sean Kleier', 'Ashley Williams', 'Brooke Smith', 'Rosemary Dunsmore'],
 '/lifetime-chris-watts-poster.png',
 '/lifetime-chris-watts-backdrop.png',
 'The story of Chris Watts, who murdered his pregnant wife and two daughters.',
 'The story of Chris Watts, who confessed to murdering his pregnant wife and two young daughters.'),

(83, 'The Clark Sisters: First Ladies of Gospel', 2020, 7.5, '87 min',
 ARRAY['Biography', 'Drama', 'Music'],
 'Christine Swanson',
 ARRAY['Aunjanue Ellis', 'Kierra Sheard', 'Sheléa Frazier', 'Raven Goodwin'],
 '/lifetime-clark-sisters-poster.png',
 '/lifetime-clark-sisters-backdrop.png',
 'The story of the Clark Sisters, a gospel music group.',
 'The story of the Clark Sisters, their rise to fame, and their struggles with their mother''s strict rules.'),

(84, 'Wendy Williams: The Movie', 2021, 5.3, '87 min',
 ARRAY['Biography', 'Drama'],
 'Darren Grant',
 ARRAY['Ciera Payton', 'Morocco Omari', 'Brittney Level', 'Mike Merrill'],
 '/lifetime-wendy-williams-poster.png',
 '/lifetime-wendy-williams-backdrop.png',
 'The story of Wendy Williams, from her early career as a radio DJ to her success as a talk show host.',
 'The story of Wendy Williams'' life, her career, and her personal struggles.'),

(85, 'Salt-N-Pepa', 2021, 6.4, '87 min',
 ARRAY['Biography', 'Drama', 'Music'],
 'Mario Van Peebles',
 ARRAY['G.G. Townson', 'Laila Odom', 'Cleveland Berto', 'Monique Paul'],
 '/lifetime-salt-n-pepa-poster.png',
 '/lifetime-salt-n-pepa-backdrop.png',
 'The story of the hip-hop group Salt-N-Pepa.',
 'The story of Salt-N-Pepa, their rise to fame, and their impact on hip-hop music.'),

(86, 'Lizzie Borden Took an Ax', 2014, 5.8, '87 min',
 ARRAY['Crime', 'Drama', 'Mystery'],
 'Nick Gomez',
 ARRAY['Christina Ricci', 'Clea DuVall', 'Billy Campbell', 'Gregg Henry'],
 '/lifetime-lizzie-borden-took-an-ax-poster.png',
 '/lifetime-lizzie-borden-took-an-ax-backdrop.png',
 'A fictionalized account of the Lizzie Borden story.',
 'A fictionalized account of the infamous Lizzie Borden, who was accused of murdering her parents with an ax.'),

(87, 'The Craigslist Killer', 2011, 6.1, '87 min',
 ARRAY['Crime', 'Drama', 'Thriller'],
 'Stephen Kay',
 ARRAY['Jake McDorman', 'Torrey DeVitto', 'William Baldwin', 'Julia Campbell'],
 '/lifetime-craigslist-killer-poster.png',
 '/lifetime-craigslist-killer-backdrop.png',
 'The story of Philip Markoff, a medical student who murdered women he met on Craigslist.',
 'The story of Philip Markoff, a medical student who led a double life as a killer, using Craigslist to find his victims.'),

(88, 'Amanda Knox: Murder on Trial in Italy', 2011, 6.0, '87 min',
 ARRAY['Biography', 'Crime', 'Drama'],
 'Robert Dornhelm',
 ARRAY['Hayden Panettiere', 'Marcia Gay Harden', 'Vincent Riotta', 'Amanda Fernando Stevens'],
 '/lifetime-amanda-knox-poster.png',
 '/lifetime-amanda-knox-backdrop.png',
 'The story of Amanda Knox, who was accused of murdering her roommate in Italy.',
 'The story of Amanda Knox, an American student who was accused of murdering her roommate in Italy and the media frenzy that surrounded the case.'),

(89, 'William & Kate', 2011, 5.3, '87 min',
 ARRAY['Biography', 'Drama', 'Romance'],
 'Mark Rosman',
 ARRAY['Camilla Luddington', 'Nico Evers-Swindell', 'Samantha Whittaker', 'Jonathan Patrick Moore'],
 '/lifetime-william-kate-poster.png',
 '/lifetime-william-kate-backdrop.png',
 'The story of Prince William and Kate Middleton''s romance.',
 'The story of Prince William and Kate Middleton''s relationship, from their first meeting to their royal wedding.'),

(90, 'The Bling Ring', 2011, 5.9, '87 min',
 ARRAY['Crime', 'Drama'],
 'Michael Lembeck',
 ARRAY['Jennifer Grey', 'Austin Butler', 'Yin Chang', 'David Clayton Rogers'],
 '/lifetime-bling-ring-poster.png',
 '/lifetime-bling-ring-backdrop.png',
 'A group of teenagers burglarize the homes of celebrities in Hollywood.',
 'A group of teenagers, obsessed with celebrity culture, break into the homes of celebrities and steal their belongings.'),

(91, 'Cyberbully', 2011, 6.7, '87 min',
 ARRAY['Drama', 'Thriller'],
 'Charles Binamé',
 ARRAY['Emily Osment', 'Kelly Rowan', 'Kay Panabaker', 'Meaghan Rath'],
 '/lifetime-cyberbully-poster.png',
 '/lifetime-cyberbully-backdrop.png',
 'A teenage girl is cyberbullied after receiving a laptop for her birthday.',
 'A teenage girl is subjected to online harassment and bullying after receiving a laptop for her birthday.'),

(92, 'Five', 2011, 6.8, '87 min',
 ARRAY['Drama'],
 'Jennifer Aniston',
 ARRAY['Patricia Clarkson', 'Jeanne Tripplehorn', 'Rosario Dawson', 'Lyndsy Fonseca'],
 '/lifetime-five-poster.png',
 '/lifetime-five-backdrop.png',
 'Five short films about women dealing with breast cancer.',
 'Five short films that explore the impact of breast cancer on women''s lives.'),

(93, 'Magic Beyond Words: The J.K. Rowling Story', 2011, 5.7, '87 min',
 ARRAY['Biography', 'Drama'],
 'Paul A. Kaufman',
 ARRAY['Poppy Montgomery', 'Antonio Cupo', 'Emily Holmes', 'Michelle Harrison'],
 '/lifetime-magic-beyond-words-poster.png',
 '/lifetime-magic-beyond-words-backdrop.png',
 'The story of J.K. Rowling, the author of the Harry Potter series.',
 'The story of J.K. Rowling''s life, from her struggles as a single mother to her success as the author of the Harry Potter series.'),

(94, 'Dirty Little Secret', 2014, 6.4, '87 min',
 ARRAY['Drama', 'Thriller'],
 'Penelope Buitenhuis',
 ARRAY['Melissa Gilbert', 'J
